pipeline {
  agent {
    label "master"
  }
  environment {
    CI = "true"
    NOW = "${new Date()}"
    IMAGE = "tfwdev/moncher"
    CLUSTER = "tfwdev-ECSCluster-1DK98N03E2Y73"
    SERVICE = "tfw-moncher"
  }
  stages {
    stage("Build") {
      agent {
        docker {
          image "node:12.13.0-alpine"
          args "--tmpfs /.npm"
          reuseNode true
        }
      }
      steps {
        sh "yarn install"
        sh "yarn add @tfwdev/platform@snapshot"
        sh "sed -i.bak \"s/non-ci-build/$NOW/\" src/build.ts"
        sh "yarn build"
        sh "yarn webpack"
        sh "mv src/build.ts.bak src/build.ts"
      }
    }
    stage("Cleanup") {
      steps {
        sh "git checkout package.json yarn.lock"
      }
    }
    // stage("Test") {
    //   steps {
    //     sh "yarn test"
    //   }
    // }
    stage("Image") {
      steps {
        configFileProvider([configFile(fileId: 'firebase-creds',
                                       targetLocation: 'firebase-creds.json')]) {
          script {
            docker.build("$IMAGE", "-f etc/Dockerfile .")
          }
        }
      }
    }
    stage("Publish") {
      steps {
        script {
          docker.withRegistry("https://733329275076.dkr.ecr.us-east-2.amazonaws.com",
                              "ecr:us-east-2:aws-jenkins") {
            docker.image("$IMAGE").push("latest")
          }
        }
      }
    }
    stage("Deploy") {
      steps {
        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-jenkins']]) {
          sh "aws --region us-east-2 ecs update-service --cluster $CLUSTER --service $SERVICE --force-new-deployment"
        }
      }
    }
  }
  post {
    failure {
      slackSend(
        color: "#FF9FA1",
        message: "Jenkins build failed: `${env.JOB_NAME}` #${env.BUILD_NUMBER}:\n${env.RUN_DISPLAY_URL}")
    }
  }
}
